CREATE TABLE EMP_BACKUP(
EMP_NAME VARCHAR(20) NOT NULL,
EMP_ID INTEGER PRIMARY KEY NOT NULL,
DESIGNATION VARCHAR(10) NOT NULL,
GENDER CHAR(1),
MOB_NO VARCHAR(10),
USERNAME VARCHAR(25) NOT NULL,
PASSWORD VARCHAR(20) NOT NULL
);

DELIMITER //
CREATE TRIGGER TRIG_EMP
BEFORE DELETE ON EMPLOYEE
FOR EACH ROW
BEGIN
INSERT INTO EMP_BACKUP(EMP_NAME,EMP_ID,DESIGNATION,GENDER,MOB_NO,USERNAME) VALUES (OLD.EMP_NAME,OLD.EMP_ID,OLD.DESIGNATION,OLD.GENDER,OLD.MOB_NO,OLD.USERNAME);
END;
//
